### ISSUE TITLE
latest browsers on windows 7

### ISSUE THREAD

**Issue by krimnassim** [vxiiduu/VxKex#103]
hi,how to install latest brave browser on windows 7 32bit?

**Comment by MasterMando0** [comment]
Well dude, I'm not too sure, the kernel extension for Windows 7 isn't that great and the newer versions of Brave may not work. I found a modern browser that works for Windows 7 and it is called Supermium which is based on Chromium and now it is on version 119.0. I know that might be not what you may be looking for but it is worth it. Ask me for any more questions or if you want a better browser. good luck bud

**Comment by informatorius** [comment]
Firefox browser 115 ESR still supported on Windows 7 officially until September 2024.

**Comment by ask2018** [comment]
@krimnassim for Brave you can try here https://github.com/Blaukovitch/GOOGLE_CHROME_Windows_7_CRACK/releases/tag/brave
or here https://github.com/adeii/supermium-portable/releases/tag/v1.61

**Comment by jonm58** [comment]
https://github.com/Eclipse-Community/r3dfox/releases/
