### ISSUE TITLE
qBittorrent crash due to Mirillis Action hooks

### ISSUE THREAD

**Issue by Templayer** [vxiiduu/VxKex#111]
Shit, qBittorrent just crashed.

![image](https://github.com/vxiiduu/VxKex/assets/11728067/09edaf01-d392-4e9e-877a-a323d090082a)

[qbittorrent-00133538934712917768.zip](https://github.com/vxiiduu/VxKex/files/14472673/qbittorrent-00133538934712917768.zip)

The logs reveal the reason - Mirillis Action (which you can download a trial version for) is a recording software (far superior to garbage like OBS) and it does directx hooks. I'm not running Mirillis Action under VxKex (no need for now, they still support Win7), and it causes VxKex applications to crash on unimplemented things.

**Comment by vxiiduu** [comment]
Can you check the folder of the Action recorder and find the place where action_x64.dll is. See if there is another DLL called action_x86.dll as well. I will block DLL import rewriting on these two DLLs and then you can check whether this fixes the problem.

**Comment by Templayer** [comment]
![image](https://github.com/vxiiduu/VxKex/assets/11728067/c385c233-411c-47c9-b57a-f3be170758f4)

Yup, that certainly seems to be the case.

Please, also be aware that Mirillis Action might drop Win7 support soon (I'm not sure), so we might need VxKex to be appliable to it in the (possibly near) future.

**Comment by vxiiduu** [comment]
This is build 1004 which prevents DLL import rewriting for those two DLLs.
[KexSetup_Release.zip](https://github.com/vxiiduu/VxKex/files/14472890/KexSetup_Release.zip)

Keep in mind that most screen recording software such as OBS and Action is not a priority for VxKex. If they drop support, it's much better just use an old version.

**Comment by vxiiduu** [comment]
Well, considering that they still claim Windows Vista support on the web page, I think Win7 is still fine for now. Glad you are no longer having the crashing problems.
