### ISSUE TITLE
Miru fails

### ISSUE THREAD

**Issue by i486** [vxiiduu/VxKex#114]
```
---------------------------
Miru.exe - Entry Point Not Found
---------------------------
The procedure entry point GetPackageFamilyName could not be located in the dynamic link library kxbase. 
---------------------------
OK   
---------------------------

```

https://github.com/ThaUnknown/miru

**Comment by vxiiduu** [comment]
Unfortunately this seems to be an electron application. See if supermium electron can help you get it running.

**Comment by i486** [comment]
Works with latest version

![image](https://github.com/vxiiduu/VxKex/assets/625325/2a600e0d-e8a3-4871-991f-b2d0b87e8293)

Insane stuff @vxiiduu
