### ISSUE TITLE
Rockstar games report

### ISSUE THREAD

**Issue by cutiegin** [vxiiduu/VxKex#120]
![image](https://github.com/vxiiduu/VxKex/assets/115403340/538a1bd1-bd30-4cb3-82b7-dbbb0744063e)
programm cant run because on computer isnt avaliable kxuser.DLL try to reinstall programm, so RGL/launcher can be installed with VxKex But i cant run it

**Comment by vxiiduu** [comment]
you can try again with new release 1.1.0.1291

![image](https://github.com/vxiiduu/VxKex/assets/73044267/b712f4b4-623b-4f51-943f-4aa774c1fa76)

the installer seems to be very buggy, but it is possible to get it installed

**Comment by cutiegin** [comment]
no, it`s still not working
