### ISSUE TITLE
The new release detected as a trojan ?

### ISSUE THREAD

**Issue by Steerlock** [vxiiduu/VxKex#122]
![image](https://github.com/vxiiduu/VxKex/assets/163396568/d27cdcbd-6f1e-484e-a8d6-2552b2628f7f)

Uploading the file to virustotal indicates that it's a trojan, and although it might be a false positive, it's worth looking into it.

uploaded_file: KexSetup_Release_1_0_0_999.exe

**Comment by Raptor007** [comment]
Not sure if it's another false positive, but MSE is detecting "Trojan:Win32/Casdet!rfn" in the current 1.1.1.1375 release.
![trojan-win32-casdet-rfn](https://github.com/vxiiduu/VxKex/assets/421848/59722d9d-2bd2-4365-b480-c75479496766)
