### ISSUE TITLE
Spotify post 1.2.5.1006

### ISSUE THREAD

**Issue by BurnedPinguin** [vxiiduu/VxKex#124]
Spotify deprecated Windows 7 after 1.2.5.1006. Trying to run any version after that without VxKex asks for api-ms-win-core-winrt-l1-1-0.dll, and running it with VxKex, it asks for api-ms-win-core-toolhelp-l1-1-0.dll. I cannot find out which function it's calling from it, as I don't know how. If you'd like me to find that out, please instruct me and I'll get back ASAP.

**Comment by vxiiduu** [comment]
Latest spotify will be supported in the next release, which is coming soon.
![image](https://github.com/vxiiduu/VxKex/assets/73044267/e2792575-74c3-41cd-9d1d-e4db8f567dc3)

**Comment by vxiiduu** [comment]
With the release of [version 1.1.0.1291](https://github.com/vxiiduu/VxKex/releases/tag/Version1.1.0.1291), Spotify is now supported.

**Comment by BurnedPinguin** [comment]
Trying with 1.1.0.1291, it now complains about NETAPI32.DLL.
![image](https://github.com/vxiiduu/VxKex/assets/77156464/e6d0d663-8b7b-4f7c-9d4e-191b91dd9f1f)
