### ISSUE TITLE
Signal doesn't work vith VxKex

### ISSUE THREAD

**Issue by maciekos95** [vxiiduu/VxKex#128]
I tried to install Signal desktop app, which is currently limited to Windows 10 and 11. After enabling VxKex and spoofing Windows 10, the installer worked properly and the main Signal app was installed. Unfortunately, I can't open it. Without VxKex enabled, it throws some error related to KERNEL32.dll. So, I enabled vxKex for the Signal exe file and this error disappeared, but now I have a new JavaScript error, which is shown on the attached screenshot. As far as I remember, Signal desktop app is built on Electron, so it has to work with VxKex theoretically.

![image](https://github.com/vxiiduu/VxKex/assets/25316541/852f742f-acbd-4bed-81b5-2fb8bfefe2f7)

**Comment by vxiiduu** [comment]
This appears to be a common error with a certain class of Electron app that uses libuv. It will be fixed in the next release. Thanks for letting me know, I'll attempt to test Signal and get it working before I release another version of vxkex.

**Comment by maciekos95** [comment]
Thanks for the quick reply ;) I'll be waiting for the next release.

**Comment by CommonLoon102** [comment]
You are doing God's work.

**Comment by vxiiduu** [comment]
With the release of 1.1.1.1375, this issue should now be fixed. Feel free to re-open the issue if there are still problems.

**Comment by maciekos95** [comment]
With the newest version of VxKex Signal app finally launched properly, but it shows a yellow nag telling that Signal on my computer is still to reach end of support in June 2024 (a similar nag was displayed last year when Signal was dropping Windows 7 support, but then there was a final date of August 2023).

Unfortunately, I had to uninstall the newest VxKex version and replace it with the older one, because with the new one my Brave browser refuses to show any website (or even settings and new tab page).
