### ISSUE TITLE
[question] If i install it on Windows 8.1, will it work for Windows 10 programs?

### ISSUE THREAD

**Issue by LeBrick-Studio** [vxiiduu/VxKex#14]
I'm looking for a project like this for Windows 8.1 (to run some of the programs that ask for Win10). If I try to install VxKex on 8.1, will it break the system?

**Comment by mina354** [comment]
No.

**Comment by vxiiduu** [comment]
VxKex is not intended for any Windows version other than 7. I haven't tested it on 8 and 8.1, and I don't know whether it will work or not. But it will probably not break the system.
