### ISSUE TITLE
Spotify is now broken again

### ISSUE THREAD

**Issue by BurnedPinguin** [vxiiduu/VxKex#143]
![image](https://github.com/vxiiduu/VxKex/assets/77156464/0ec92074-4585-45f6-a11e-444abbd1de2c)

The same version of Spotify that was latest at the time of VxKex release 1.1.0.1291 and worked with it, is now broken with 1.1.1.1375, and it exhibits the same error (see image) as many other applications in this new release do (for more details on the error see: https://github.com/vxiiduu/VxKex/issues/139)

**Comment by vxiiduu** [comment]
Can you post all the logs from broken programs. Located in %localappdata%\vxkex\logs

**Comment by BurnedPinguin** [comment]
My apologies. Every program crash I saw with 0xc0000142 were because my AV kept breaking my VxKex installs. Disabling the AV and reinstalling fixes this specific error.
