### ISSUE TITLE
Would creation of a separate OS spoofer app be possible?

### ISSUE THREAD

**Issue by Oreeeee** [vxiiduu/VxKex#15]
For example, some apps can run on Windows XP but their checks block installation on Windows XP.

**Comment by vxiiduu** [comment]
Yes, the method that VxKex uses to spoof versions can be used standalone. The main hurdles are:
- Some apps don't use the version functions to figure out the OS version, they do random stuff like attempt to load a DLL and if it fails, assume the windows version is too old
- Some apps, especially installers, extract .exe files to some temporary location before running them, so you need to hook CreateProcessInternalW to apply version spoofing to child processes as well
