### ISSUE TITLE
[Not Working] Upscayl

### ISSUE THREAD

**Issue by CommanderLake** [vxiiduu/VxKex#172]
The application was unable to start correctly (0xc00000fd)
[Upscayl-00133566925875300000-9900.zip](https://github.com/vxiiduu/VxKex/files/14863602/Upscayl-00133566925875300000-9900.zip)

**Comment by CommanderLake** [comment]
Actually this may be part of a bigger issue I'm having because programs that previously worked now don't work like qBittorrent.

**Comment by CommanderLake** [comment]
There are 2 errors early in the log of anything i try, sure its only me having the issue but 0.0.0.3 did work where the latest doesn't.

**Comment by vxiiduu** [comment]
@CommanderLake Where is VxKex installed?

**Comment by CommanderLake** [comment]
The default location.

**Comment by vxiiduu** [comment]
I have confirmed a bug in VxKex which was causing this issue. It will be fixed in the next release. Thanks for reporting it.

**Comment by CommanderLake** [comment]
Any workarounds I can try till then?

**Comment by vxiiduu** [comment]
You can use this and see if it fixes the problem.

[KexSetup_Release.zip](https://github.com/vxiiduu/VxKex/files/14879123/KexSetup_Release.zip)

**Comment by CommanderLake** [comment]
Yes that fixes it!
