### ISSUE TITLE
Oculus PCVR Support???

### ISSUE THREAD

**Issue by Skylake013** [vxiiduu/VxKex#182]
i've tried running the installer, when it finished it would tell me some error happened and i need to reinstall, (ive reinstalled many times it doesnt work) even with VxKex enabled with windows 10 reporting with stonger version reporting enabled, and doesnt work. i have another windows 11 drive that has the oculus app installed on it (it works flawless) so i tried running the OculusClient.exe with vxkex, windows 10 and stonger version reporting, it tells me i need to update the app but when i click update it just brings me back to the oculus setup, i do NOT want anyone saying "just use windows 10", "its not supported" or "just dont use an oculus" smth like that, i would like an informative response, please. 
![Capture](https://github.com/vxiiduu/VxKex/assets/104372914/1bbb6278-b950-46ae-b683-0be5f4cc30c6)

**Comment by MuhammedEmirArtan** [comment]
i dont know about ur problem but what build you are using? can you give a link?

**Comment by NetImmerse** [comment]
use [ALVR](https://github.com/alvr-org/ALVRl) instead, get your Quest into development mode and sideload the client vie SideQuest. 
works fine even without VxKex (checked version 20.6.1, not guaranteed on later versions).

**Comment by Skylake013** [comment]
> use [ALVR](https://github.com/alvr-org/ALVR) instead, get your Quest into development mode and sideload the client vie SideQuest. works fine even without VxKex (checked version 20.6.1, not guaranteed on later versions).

ive been having issues with ALVR recently and my wifi isn't the BEST, but the only problem is that i need to play

**Comment by Skylake013** [comment]
> use [ALVR](https://github.com/alvr-org/ALVR) instead, get your Quest into development mode and sideload the client vie SideQuest. works fine even without VxKex (checked version 20.6.1, not guaranteed on later versions).

Ive been having issues with ALVR recently and my wifi isn't the BEST, but i need to play angame that is Oculus-exclusive and ALVR only works with Steam (Revive doesn't work)

**Comment by Skylake013** [comment]
> i dont know about ur problem but what build you are using? can you give a link?

its a prebuilt HP Pavilion 690-03xx, GTX 1050, 16GB RAM, Ryzen 5 2600, Windows 7 SP1 with updates Up to january 2020, the ISO is Windows 7 Updated V4 by k4sum1

**Comment by Arkanu-of-Galatiel** [comment]
Any ideas for the CV1 Oculus Rift?
