### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by wealstarr** [vxiiduu/VxKex#184]
Hello,

Wanted to use the newer Firefox browser and discovered that Kex has support for it but when I try to install the Kex, two error messages shows up and installation fails.

![Capture](https://github.com/vxiiduu/VxKex/assets/26643729/d75e7fdc-b261-4b15-a85c-e8220598d717)

When I click Okay, then this shows up

![Capture2](https://github.com/vxiiduu/VxKex/assets/26643729/4addc481-03b0-405b-891e-9cb39e9a0e56)

Please note: OS is Windows 8.1 (x64) with all the latest updates.

Is there any work around to get Kex working ?

Any help will be greatly appreciated.

**Comment by vxiiduu** [comment]
Not supported on 8.1, sorry.

**Comment by ideapc** [comment]
Why is the source closed? No once can port it to W8.1 without having the source

**Comment by vxiiduu** [comment]
@ideapc If you didn't skim the readme or take 5 seconds to look at the releases page then you weren't ever going to port anything to 8.1 to begin with
