### ISSUE TITLE
can I use mpv.net v7.1.1.0 with .NET Desktop Runtime 6.0 on Windows 7?

### ISSUE THREAD

**Issue by candrapersada** [vxiiduu/VxKex#196]
can I use mpv.net v7.1.1.0 on Windows 7?
https://github.com/vxiiduu/VxKex/blob/ca996fd1786756aebc0905f994834ffc64d285e3/README.md?plain=1#L53

**Comment by CommonLoon102** [comment]
.NET 6 Desktop works on Windows 7, even without ESU updates. So, yes.
