### ISSUE TITLE
Latest VxKex can't be build from source with Visual Studio 2010, I tried both "Batch Build" and "Build Solution".

### ISSUE THREAD

**Issue by MasterSlenderTR** [vxiiduu/VxKex#21]
![unknown](https://user-images.githubusercontent.com/50411937/174196831-d7f8973e-fe19-49d6-a8e2-1ac57d9da1a3.png)
![unknownn](https://user-images.githubusercontent.com/50411937/174196835-bdb85315-497d-40d7-b43c-374e1d6b31cb.png)

**Comment by sydia1103** [comment]
You need Visual Studio 2010 SP1. 2010 with no service pack is known to have this bug.

**Comment by MasterSlenderTR** [comment]
Thanks, I was able to compile it with sp1.
