### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by IvanFed08** [vxiiduu/VxKex#22]
How to install VxKex Windows 7? What programs are needed to install and so on, please tell me!

**Comment by WhiteRedDragons** [comment]
Hi, I'm a bit late.
So I just got this thing to compile. For this I required to get the Win7.1 SDK and the WDK7.1
Then first Microsoft Visual Studio 2010 and then ms VS2010**SP1**. It was insanely hard finding this as Microsoft took down their download... "Upgrading" the solution to newer build tools just seems to break more things than it is worth it. Using the v100 toolset with VS2010sp1 appears to be the only way that I could find. Once you have the 64bit toolset installed using this you can however use newer vs versions, I personally got it to work with vs2019 but that is rather useless unless you are planning on doing actual programming on it.
Needless to say you need to compile the code and then run the kexsetup compiled into the release folder.

**Comment by vxiiduu** [comment]
Just download the latest release from the releases page, run KexSetup and follow the prompts. If you encounter any other problems with this setup program then you need to be more specific
