### ISSUE TITLE
is it possible to get latest handbrake to work on windows 7

### ISSUE THREAD

**Issue by Chuterix** [vxiiduu/VxKex#25]
i upgraded vxkex to latest version 0.0.0.3
top image: installer
bottom image: portable
i ran both with vxkex enabled and windows 10 reported, yet it still says i can't run handbrake
debugger enabled:
![kex](https://user-images.githubusercontent.com/62620653/186016473-f1ac61d8-9cd6-4056-8173-314f5ccfa1e0.png)
![kex2](https://user-images.githubusercontent.com/62620653/186016481-cad5a28e-195d-4d45-8b77-201b3bc945ad.png)

**Comment by ChutacoackoPlayz** [comment]
i actually used wrong version, but both programs still don't work but don't display the unsupported os message anymore.

**Comment by vxiiduu** [comment]
The latest version of HandBrake now works with the new updated version of VxKex.
