### ISSUE TITLE
Request for Licensing Information for the source code and the dll

### ISSUE THREAD

**Issue by 1821746019** [vxiiduu/VxKex#266]
@vxiiduu
Dear vxiiduu,

I am interested in using the VxKex library for my personal business project to make my Qt6 app available on win7, and would like to ensure compliance with the appropriate licensing terms. Could you please clarify the licensing terms under which the the library is distributed? Specifying a license would greatly help in understanding how this library can be legally used and distributed.

Thank you for your work and I look forward to your response.

Best regards

**Comment by i486** [comment]
You're on wrong repo

qt6windows7
https://github.com/crystalidea/qt6windows7/

**Comment by 1821746019** [comment]
@i486
I appreciate your response, but I must clarify that I have already tried the repository you mentioned. While it functions well with Qt Widget applications, it does not perform adequately with Qt Quick applications.
VxKex performs adequately with the both.

**Comment by vxiiduu** [comment]
If you are working towards making applications compatible with Windows 7 then you can take any VxKex code and use it however you want. All source code files in the VxKex repository are written by me. However, take note that some of the DLLs in the prebuilt DLLs folder come from Microsoft.

**Comment by 1821746019** [comment]
@vxiiduu

OK, thank you very much for your contributions. I will take note of your caution regarding the DLLs from Microsoft.
