### ISSUE TITLE
[Working] Signal 7.15.0

### ISSUE THREAD

**Issue by hubstedt** [vxiiduu/VxKex#277]
The error I get trying to launch the current version of Signal (signal-desktop-win-7.15.0.exe)
Same error with 7.13, 7.14.

Render process is gone

Error: Reason: launch-failed, Exit Code: 63
    at App.<anonymous> ([REDACTED]\app\global_errors.js:88:7)
    at App.emit (node:events:518:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83836)
    at WebContents.emit (node:events:518:28)

**Comment by CopperFr** [comment]
Seems to launch with my version https://github.com/vxiiduu/VxKex/issues/267#issuecomment-2196359451

**Comment by hubstedt** [comment]
Where did this version of VxKex come from?

**Comment by CopperFr** [comment]
This is my own build of  VxKex with some improvement

**Comment by hubstedt** [comment]
Thanks for the info but that's not going to help me at this point.

**Comment by CopperFr** [comment]
It can helps you as I've made some changes that makes it launch (I've seen QR Code)

**Comment by hubstedt** [comment]
Trying again with current version:
signal-desktop-win-7.15.0.exe

**Comment by hubstedt** [comment]
Not sure what happened but after reinstalling (and maybe a reboot?) Signal 7.15.0 is working using VxKex on Windows 7.  Wish I had more to report.
