### ISSUE TITLE
Star Citizen 32-bit DLL 'icudt59.dll' was loaded into a 64-bit application

### ISSUE THREAD

**Issue by CommanderLake** [vxiiduu/VxKex#46]
Star Citizen used to run on 7 but after an update a while back it gives this error:
The procedure entry point SetThreadInformation could not be located in the dynamic link library KERNEL32.dll.

Using the latest Kex release I get this before it terminates:
The 32-bit DLL 'icudt59.dll' was loaded into a 64-bit application.
Architecture of DLLs and applications must match for successful program operation.

icudt59.dll has only resources and no code, is this error terminating the program or is it likely terminating due to another error? Can I ignore this message and have it continue anyway?

**Comment by okt04175** [comment]
Use CFF Explorer to modify the dll file's import, ( SetThreadInformation ) change to ( SetLastError ) .

**Comment by CommanderLake** [comment]
Thanks, now it wants GetSystemTimePreciseAsFileTime, what should i change that one to?

**Comment by CommanderLake** [comment]
I cant modify the game files because it uses EAC.

**Comment by okt04175** [comment]
For Win7:
GetSystemTimePreciseAsFileTime >> GetSystemTimeAsFileTime

**Comment by jackbingow** [comment]
@okt04175 where your Windows 7 fix for Uncharted 4?

**Comment by okt04175** [comment]
> @okt04175 where your Windows 7 fix for Uncharted 4?
> 
> KERNEL32.dll SetThreadDescription function replace with which? user32.dll GetWindowDpiAwarenessContext function replace with which? GetAwarenessFromDpiAwarenessContext function replace with which? GetDpiForSystem function replace with which? VxKex crash on KERNEL32.dll with c000..05 error in log

I have no idea to fix that.

At least I know ( SetThreadDescription ) can replace with ( SetLastError ).

**Comment by jackbingow** [comment]
@okt04175 I managed with CFF explorer to replace with MessageBoxW
user32.dll GetWindowDpiAwarenessContext function
GetAwarenessFromDpiAwarenessContext function 
GetDpiForSystem function 
remove api... import
put vkproton d3d12,dxvk in root
But it requires FEATURE_LEVEL=12_0 to be present even d3d12 converter to vulkan present.
Your fix for spiderman does had this error in past?

**Comment by okt04175** [comment]
> @okt04175 I managed with CFF explorer to replace with MessageBoxW user32.dll GetWindowDpiAwarenessContext function GetAwarenessFromDpiAwarenessContext function GetDpiForSystem function remove api... import put vkproton d3d12,dxvk in root But it requires FEATURE_LEVEL=12_0 to be present even d3d12 converter to vulkan present. Your fix for spiderman does had this error in past?

Spider-Man Remaster haven't this error.

**Comment by Saswat2005** [comment]
Is it same for OneDrive? OneDrive has the same SetThreadInformation in kernel32. dll

**Comment by CommanderLake** [comment]
What about the second issue:
Using the latest Kex release I get this before it terminates:
The 32-bit DLL 'icudt59.dll' was loaded into a 64-bit application.
Architecture of DLLs and applications must match for successful program operation.
icudt59.dll has only resources and no executable code.
