### ISSUE TITLE
DBG or Rel?

### ISSUE THREAD

**Issue by Seedy-Threepio** [vxiiduu/VxKex#54]
This isn't an issue per se, but I wasn't sure on the best way to contact you about this.
There are 2 setup executables for each release, DBG and Rel. Which one should I use? The readme.txt file is the most vague document I've ever seen.

**Comment by Smu1zel** [comment]
> This isn't an issue per se, but I wasn't sure on the best way to contact you about this. There are 2 setup executables for each release, DBG and Rel. Which one should I use? The readme.txt file is the most vague document I've ever seen.

Dbg stands for Debug, intended if you want to help report a bug or want extra info to troubleshoot. Rel is Release and intended for general use, but both should not differ in what apps they can run.

**Comment by vxiiduu** [comment]
Use the Rel version.
