### ISSUE TITLE
Request: build instructions

### ISSUE THREAD

**Issue by Seedy-Threepio** [vxiiduu/VxKex#55]
Could you please add some detailed build instructions to the readme, including what is required to compile the source files, steps on generating both the VxKex binaries and the DBG and REL installers?
Thanks.

**Comment by Saswat2005** [comment]
No worries. If I will be creating an API binaries for Windows Vista, and this API Extension for Windows Vista will be called Vistara. But theoretically not possible, or it will. 

Windows 8 Extended Kernel is based on Windows 10 build 9888, with all Windows 8 look.

**Comment by Seedy-Threepio** [comment]
Windows Vista [already has an extended kernel project](https://ximonite.com/win32/index.html).

**Comment by Saswat2005** [comment]
I know that. But I want that for Windows 7!

**Comment by ImGGAAVVIINN** [comment]
um, so how do I build it?

**Comment by rastilin** [comment]
I think you'll need Visual Studio 2010 with SP1. I had trouble tracking down the Service Pack but the [Internet Archive had a copy](https://archive.org/details/vs-2010-sp-1dvd-1). Though I haven't had a chance to try it since finding the link. 

This project absolutely needs build instructions as otherwise it's basically impossible to contribute.

**Comment by Seedy-Threepio** [comment]
The lack of a response from the developer on this is concerning, to say the least.

**Comment by vxiiduu** [comment]
The Visual Studio 2010 (Professional/Ultimate) installer disk can be found from various torrent websites.
The SP1 installer disk can be found from Internet Archive as stated earlier.
After installing Visual Studio 2010 with SP1, open the .sln file and press F7 to build.
Success is not 100% guaranteed unless you use the source code of an already-released version (0.0.0.1, 0.0.0.2, or 0.0.0.3).

**Comment by Saswat2005** [comment]
Vxiiduu, please kindly make a build no 0.0.0.4 such that all the dll errors will be vanished away!

**Comment by Artoria2e5** [comment]
It miiight be a good idea to grab whatever headers from msvc 10 that made it work and put it in the repo.

**Comment by Artoria2e5** [comment]
Huh you know what? It builds in VS2019 after veery minor changes. A PR is overkill because I don't even have a Win7 to test it against, but the patch and the build files are attached for anyone who wants to try.
[0001-Placating-VS-2019-It-s-easy.zip](https://github.com/vxiiduu/VxKex/files/11484861/0001-Placating-VS-2019-It-s-easy.zip)
[VxKex-vs2019-artifacts.zip](https://github.com/vxiiduu/VxKex/files/11484888/VxKex-vs2019-artifacts.zip)

Yes, using the artifacts zip is a case of "running a stranger's dll at the highest permission level possible".

**Comment by Artoria2e5** [comment]
@rastilin hey uh, have you checked whether the dll works? I know it's a lot to ask, but if it works I can cross-post the comment to #2.

And if it doesn't I will need to tinkle with /SUBSYSTEM settings or something.

**Comment by rastilin** [comment]
> @rastilin hey uh, have you checked whether the dll works? I know it's a lot to ask, but if it works I can cross-post the comment to #2.
> 
> And if it doesn't I will need to tinkle with /SUBSYSTEM settings or something.

Not yet, but I will ASAP and I'll report back afterward.

**Comment by rastilin** [comment]
@Artoria2e5 It seems to build. I'm not sure how I should go about testing it.

One thing I noticed is that the KexDll tries to build after the KexGui, which causes an error; but if you build them both manually the solution as a whole builds fine after that. 

It might be worth putting together a CMakeLists file for the project to build it with GCC. There's a project called cmakeconverter that might be able to convert the sub-projects.

**Comment by vxiiduu** [comment]
@rastilin The current rewrite is unfinished and there are no implemented extended functions so you cannot actually use it. If you want to do some development on your own I can give you an overview of what still needs to be done, but if you are just trying to use it, do not bother with trying to build from sources.

**Comment by Artoria2e5** [comment]
@vxiiduu The patch includes a gitignore file. You may want to get that one added to your current tree so you don't need to waste time removing the built files from your comment.

**Comment by rastilin** [comment]
> @rastilin The current rewrite is unfinished and there are no implemented extended functions so you cannot actually use it. If you want to do some development on your own I can give you an overview of what still needs to be done, but if you are just trying to use it, do not bother with trying to build from sources.

Absolutely, I'm keen to try helping. I'm not great at C++ but if you point out something that needs to be implemented I'll try to figure it out.

**Comment by vxiiduu** [comment]
@Artoria2e5 I already have a .bat script to prepare the source tree for releases, it's the Cleanup.bat one. All you need to do is click it

@rastilin I will explain the key details of VxKex operation here. Any further information is something that you should find out by exploring the source code, which I believe to be fairly well commented (although do feel free to ask more questions if there's something you really don't understand).

Basically, VxKex works by rewriting the import tables of target applications and the DLLs the target applications depend on. For example, if an application wants kernel32.dll, VxKex will rewrite it to kernel33.dll (which is provided by VxKex and contains extended functions from windows 8, 8.1, 10 etc.).
The way VxKex accomplishes this task of rewriting import tables is by loading KexDll into every target application before the application starts. Specifically, the DLL is loaded as an Application Verifier provider (Image File Execution Options and VerifierDlls are two keywords that you can search for if you want more information).
Naturally you should look in KexDll's "dllmain.c" source file to see what happens immediately after KexDll gets loaded. You should be able to figure out all other details from there.

**Comment by Artoria2e5** [comment]
> @Artoria2e5 I already have a .bat script to prepare the source tree for releases, it's the Cleanup.bat one. All you need to do is click it

well, the point of gitignore is that you don't need to destroy your build cache to make it ready for github...

**Comment by vxiiduu** [comment]
> well, the point of gitignore is that you don't need to destroy your build cache to make it ready for github...

This is off topic, but vxkex isn't really a git project. It's a visual studio project that I drag and drop onto github because it's the most popular platform for releasing software. I want to be able to release copies of the sources to other people and/or websites without having to delete the irrelevant .git and .gitignore folders (which would necessitate a cleanup.bat anyway).

**Comment by Saswat2005** [comment]
VxKex version 0.0.1 then 0.1 then 1 will be released, as you can run apps compatible with Windows 10 or above on Windows 7, just like OneCore API on Windows XP, running apps compatible with Windows 8 or above.

**Comment by Saswat2005** [comment]
Anyways, Windows 7 is better than Windows Vista, as Windows Vista sucked..........
