### ISSUE TITLE
VxKex tab doesn't appear in system properties

### ISSUE THREAD

**Issue by SkyDaHaloGuy** [vxiiduu/VxKex#69]
I downloaded and installed using the x64.exe of the 0.0.0.3 release but I can't seem to find the properties tab it's supposed to be in. Is there anything specific I need to do before I install? Any help at all would be greatly appreciated. (Just using Steam as an example)

![Capture](https://user-images.githubusercontent.com/128020176/230251835-c6f7ed7d-3c8e-4147-b42e-fd1d226746b2.PNG)

**Comment by tamr** [comment]
> This time the 32 bit setups are not included

The tab appears when you launch it under x64. If you are using Total commander, try checking the properties in totalcmd64.exe. Or you can launch it with the loader c:\Program Files\VxKex\VXKEXLDR.EXE.
Btw, it seems it stores programs settings as filenames somewhere. I've tried to test with chrome.exe, set the windows version to 10 and it was a disaster. It didn't work, and attempting to launch any other Chromium browser crashed leaving hundreds of chrome.exe processes (with debugger attached).

**Comment by vxiiduu** [comment]
The old version of VxKex didn't support using properties on a shortcut file. The new version works fine in this situation, so this shouldn't be a problem anymore.
