### ISSUE TITLE
Error during the build of vxkex

### ISSUE THREAD

**Issue by 25495** [vxiiduu/VxKex#7]
When i'm trying to build vkex, i got "failure during conversion to COFF: file invalid or corrupt" in visual studio 2010

**Comment by dotexe1337** [comment]
You need to manually shift some files around to get it to build properly. It puts a bunch of the dll's needed for KexSetup into the wrong folder

**Comment by 25495** [comment]
which files ?

**Comment by dotexe1337** [comment]
Copy all the files from /Debug and /x64/Debug into /KexSetup/Debug (you will have to create that folder as it doesnt exist)

**Comment by 25495** [comment]
i cannot do

**Comment by 25495** [comment]
can someone create a guide how to compile this ?

**Comment by vxiiduu** [comment]
Install service pack 1 for visual studio 2010, it's a known bug with rtm.

**Comment by 25495** [comment]
it works, thks !
