### ISSUE TITLE
Function RtlWaitOnAddress not found in ntd33.dll when trying to run zig.exe

### ISSUE THREAD

**Issue by BumpyAHK** [vxiiduu/VxKex#73]
Trying to use the Zig programming language (specifically version zig-windows-x86_64-0.11.0-dev.2560+602029bb2) throws this error + debug log. As of Aug 10, 2020, Zig builds stopped working on 7 natively.

Process image full path: C:\Users\User\Desktop\zigstuff\zig.exe
Process command line: "C:\Users\User\Desktop\zigstuff\zig.exe" 
The process is 64-bit and its base address is 000000013F0C0000 (PEB base address: 000007FFFFFDA000)
[KE] Copying KexData structure to child process
[KE] Rewriting imports of executable file
    Rewriting DLL import ole32.dll -> ole33.dll
    Rewriting DLL import KERNEL32.dll -> kernel33.dll
    Rewriting DLL import ntdll.dll -> ntd33.dll
[KE ProcId=7612, ThreadId=7028]	Process entry point: 0x000000013FAB2220, Original byte: 0x48
[KE ProcId=7612, ThreadId=7028]	Adding hard error handler at 0x000000007795ABB0. Original byte: 0x4C
[CP ProcId=7612]		Process created.
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Windows\System32\ntdll.dll
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Windows\System32\kernel32.dll
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Windows\System32\KernelBase.dll
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Program Files\VxKex\Kex64\OLE33.DLL
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Windows\System32\msvcr100.dll
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Windows\System32\ole32.dll
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Windows\System32\msvcrt.dll
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Windows\System32\gdi32.dll
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Windows\System32\user32.dll
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Windows\System32\lpk.dll
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Windows\System32\usp10.dll
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Windows\System32\rpcrt4.dll
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Windows\System32\advapi32.dll
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Windows\System32\sechost.dll
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Program Files\VxKex\Kex64\KERNEL33.DLL
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Program Files\VxKex\Kex64\KERNELBA33.DLL
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Windows\System32\shlwapi.dll
[LD ProcId=7612, ThreadId=7028]	DLL loaded: C:\Program Files\VxKex\Kex64\NTD33.DLL
[HE ProcId=7612, ThreadId=7028]	Hard Error has been raised.
    Status code: 0xc0000139 - The specified procedure could not be found.
    st=0xc0000139,dw=3028428,lpsz1=RtlWaitOnAddress,lpsz2=ntd33.dll

**Comment by Meta4245** [comment]
due to this line in the zig std source code: https://github.com/ziglang/zig/blob/0710314de6b6ab30d43a9426e58379d4827b532e/lib/std/Thread/Futex.zig#L138
RtlWaitOnAddress is for Windows 8+

**Comment by vxiiduu** [comment]
Zig is now supported and working on the latest update of VxKex.
