### ISSUE TITLE
MSVCR100.dll not found when trying to run PAINT.NET Installer

### ISSUE THREAD

**Issue by truongquangtung2020** [vxiiduu/VxKex#83]
Process image full path: C:\Users\Adam\Desktop\paint.net.5.0.6.install.anycpu.web.exe
Process command line: "C:\Users\Adam\Desktop\paint.net.5.0.6.install.anycpu.web.exe" 
The process is 32-bit and its base address is 0000000000110000 (PEB base address: 000000007EFDF000)
[KE] Copying KexData structure to child process
[KE] Rewriting imports of executable file
    Rewriting DLL import KERNEL32.dll -> kernel33.dll
    Rewriting DLL import USER32.dll -> user33.dll
[KE ProcId=3712, ThreadId=2588]	Process entry point: 0x0000000000146E51, Original byte: 0xE8
[KE ProcId=3712, ThreadId=2588]	Adding hard error handler at 0x0000000077BCA040. Original byte: 0x4C
[CP ProcId=3712]		Process created.
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\System32\ntdll.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\SysWOW64\ntdll.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\System32\wow64.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\System32\wow64win.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\System32\wow64cpu.dll
[EX ProcId=3712, ThreadId=2588]	First-chance exception occurred at 0x0000000077C060D0
    Exception code: 0x80000003: One or more arguments are invalid
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\System32\kernel32.dll
[UL ProcId=3712, ThreadId=2588]	The DLL at 0000000077A40000 was unloaded.
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\SysWOW64\kernel32.dll
[UL ProcId=3712, ThreadId=2588]	The DLL at 0000000075640000 was unloaded.
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\System32\kernel32.dll
[UL ProcId=3712, ThreadId=2588]	The DLL at 0000000077A40000 was unloaded.
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\System32\user32.dll
[UL ProcId=3712, ThreadId=2588]	The DLL at 0000000077940000 was unloaded.
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\SysWOW64\kernel32.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\SysWOW64\KernelBase.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\winsxs\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.24483_none_2b200f664577e14b\comctl32.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\SysWOW64\msvcrt.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\SysWOW64\gdi32.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\SysWOW64\user32.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\SysWOW64\advapi32.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\SysWOW64\sechost.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\SysWOW64\rpcrt4.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\SysWOW64\sspicli.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\SysWOW64\cryptbase.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\SysWOW64\lpk.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\SysWOW64\usp10.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Windows\SysWOW64\shlwapi.dll
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Program Files\VxKex\Kex32\KERNEL33.DLL
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Program Files\VxKex\Kex32\KERNELBA33.DLL
[LD ProcId=3712, ThreadId=2588]	DLL loaded: C:\Program Files\VxKex\Kex32\USER33.DLL
[HE ProcId=3712, ThreadId=2588]	Hard Error has been raised.
    Status code: 0xc0000135 - The specified module could not be found.
    st=0xc0000135,dw=3810764,lpsz1=MSVCR100.dll,lpsz2=C:\Users\Adam\Desktop;C:\Windows\system32;C:\Windows\system;C:\Windows;.;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\VxKex\Kex32

**Comment by vxiiduu** [comment]
Install the Visual C++ 2010 runtime

**Comment by truongquangtung2020** [comment]
I installed it, so I have to MSVCR100.dll to SysWOW64 bt it gets another error "The app couldn't start"

**Comment by truongquangtung2020** [comment]
The app only finds in SysWOW64 wwhile the file stored on System32

**Comment by vxiiduu** [comment]
You need to install both the 32-bit (x86) and 64-bit (x64) version of the redistributable
