### ISSUE TITLE
When "Enable VxKex" and "Show debug console" are enabled, the debug options also applies to ALL .exe with the same name, despite the file location

### ISSUE THREAD

**Issue by Kiki79250CoC** [vxiiduu/VxKex#87]
From my experience: I was torturing Firefox 117.0a1 installer some days ago (July 8) and I enabled these options on "setup.exe" and did my things without disabling the options afterwards.

Today, I was going to reinstall VS2010 on my VM and noticed that the setup.exe from the ISO refuses to launch because VxKex was interfering with it.

After suspected the July 2023 ESU updates I installed on July 12 — which wasn't that — and restored my VM twice, I started to search in the registry in order to wipe some eventual settings that applies to it and cleared the two registry places :

• `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\setup.exe`
• `HKEY_USERS\<USER_ACCOUNT_ID>\Software\VXsoft\VxKexLdr\Image File Execution Options`

And I found that the first one does not specify the path of the file, so it applies the debugging options to all `setup.exe` despite the totally different paths.

---

> _Of course I'm not expecting a patch for this bug for now, as I heard Vxiiduu is somewhat busy and don't have much time to allow to VxKex, but consider this as a possible fix if you can't run some apps because VxKex interfers with it "for an obscure reason you ignores"._

**Comment by vxiiduu** [comment]
This issue has been eliminated in the rewrite versions, as an IFEO filter is now used.
