### ISSUE TITLE
when is the next update coming out

### ISSUE THREAD

**Issue by thewanderingtraderm** [vxiiduu/VxKex#97]

**Comment by Wariables** [comment]
the trend of updates is once every few months, just wait a little

**Comment by MacncheeseTTR** [comment]
> the trend of updates is once every few months, just wait a little

But... it isn't. The last commit was 2 years ago, pretty sure its abandoned at this point, or else there would be an update.

**Comment by vxiiduu** [comment]
> when is the next update coming out?

yesterday
